### PR TITLE
[VLM] Minor corrections to VLM & GUI

### PR DESCRIPTION
**Pull request by charles-lp**
* Added missing sliders for VLM
* Import database from file to skip Euler/RANS solving loop now possible
* Fixed minor bugs of VLM integrated

### CODE REVIEW

**Comment by samayala22** [comment]
Broken ? App instantly crashes when db format "FILE" is selected. 
```
KernelBase.dll!00007ff9ca6afe7c() (Unknown Source:0)
aeroflex.exe!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 75 (d:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp:75)
aeroflex.exe!std::_Xout_of_range(const char * _Message) Line 25 (d:\a\_work\1\s\src\vctools\crt\github\stl\src\xthrow.cpp:25)
aeroflex.exe!std::unordered_map<std::string,database::airfoil,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,database::airfoil>>>::at(const std::string & _Keyval) Line 446 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\unordered_map:446)
aeroflex.exe!database::table::cl(const double alpha, const int surfaceID, const double spanLoc) Line 223 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\common\database\database.cpp:223)
aeroflex.exe!vlm::solver::nonlinear::steady::iterate$omp$1() Line 398 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\vlm\src\solver.cpp:398)
vcomp140.dll!00007ff98b711815() (Unknown Source:0)
vcomp140.dll!00007ff98b7117d9() (Unknown Source:0)
vcomp140.dll!00007ff98b71884a() (Unknown Source:0)
kernel32.dll!00007ff9cc6726bd() (Unknown Source:0)
ntdll.dll!00007ff9cce8a9f8() (Unknown Source:0)
```

**Comment by charles-lp** [comment]
> Broken ? App instantly crashes when db format "FILE" is selected.
> 
> ```
> KernelBase.dll!00007ff9ca6afe7c() (Unknown Source:0)
> aeroflex.exe!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 75 (d:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp:75)
> aeroflex.exe!std::_Xout_of_range(const char * _Message) Line 25 (d:\a\_work\1\s\src\vctools\crt\github\stl\src\xthrow.cpp:25)
> aeroflex.exe!std::unordered_map<std::string,database::airfoil,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,database::airfoil>>>::at(const std::string & _Keyval) Line 446 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\unordered_map:446)
> aeroflex.exe!database::table::cl(const double alpha, const int surfaceID, const double spanLoc) Line 223 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\common\database\database.cpp:223)
> aeroflex.exe!vlm::solver::nonlinear::steady::iterate$omp$1() Line 398 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\vlm\src\solver.cpp:398)
> vcomp140.dll!00007ff98b711815() (Unknown Source:0)
> vcomp140.dll!00007ff98b7117d9() (Unknown Source:0)
> vcomp140.dll!00007ff98b71884a() (Unknown Source:0)
> kernel32.dll!00007ff9cc6726bd() (Unknown Source:0)
> ntdll.dll!00007ff9cce8a9f8() (Unknown Source:0)
> ```

Dès que tu sélectionnes FILE, ou lorsque tu run avec l'option FILE active?

**Comment by samayala22** [comment]
> > Broken ? App instantly crashes when db format "FILE" is selected.
> > 
> > ```
> > KernelBase.dll!00007ff9ca6afe7c() (Unknown Source:0)
> > aeroflex.exe!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 75 (d:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\throw.cpp:75)
> > aeroflex.exe!std::_Xout_of_range(const char * _Message) Line 25 (d:\a\_work\1\s\src\vctools\crt\github\stl\src\xthrow.cpp:25)
> > aeroflex.exe!std::unordered_map<std::string,database::airfoil,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<std::string const ,database::airfoil>>>::at(const std::string & _Keyval) Line 446 (c:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\unordered_map:446)
> > aeroflex.exe!database::table::cl(const double alpha, const int surfaceID, const double spanLoc) Line 223 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\common\database\database.cpp:223)
> > aeroflex.exe!vlm::solver::nonlinear::steady::iterate$omp$1() Line 398 (c:\Users\samay\Documents\GitHub\AeroFLEX\src\vlm\src\solver.cpp:398)
> > vcomp140.dll!00007ff98b711815() (Unknown Source:0)
> > vcomp140.dll!00007ff98b7117d9() (Unknown Source:0)
> > vcomp140.dll!00007ff98b71884a() (Unknown Source:0)
> > kernel32.dll!00007ff9cc6726bd() (Unknown Source:0)
> > ntdll.dll!00007ff9cce8a9f8() (Unknown Source:0)
> > ```
> 
> Dès que tu sélectionnes FILE, ou lorsque tu run avec l'option FILE active?

Qd je run avec l'option.

**Comment by samayala22** [comment]
J'ai rajouté un bouton pour selectionner un fichier database si le format FILE est sélectionné mais je n'ai pas pu testé parce que c'est broken.

**Review by samayala22 — APPROVED** [review]
Good

**Pull request merged**
